In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(r"Data\FDIC_Insured_Banks.csv")
df

,OBJECTID,ADDRESBR,BRNUM,BRSERTYP,CBSABR,CBSANAMB,CITYBR,CNTRYNAB,CNTYNAMB,DEPSUMBR,...,BKMO,LOC_NAME,STATUS,SCORE,x,y,GeocodeSource,STD_ADDR_BR,STD_ADDR,ZIP4BR
0,1,22 Main Street,7636,11,25540,"Hartford-West Hartford-East Hartford, CT",Southington,United States,Hartford,76878,...,0,PointAddress,M,100.0,-72.878648,41.601435,HSIP USA_ZIP4 Composite,22 MAIN ST,100 N TRYON ST,2501
1,2,One City Center,8203,11,38860,"Portland-South Portland, ME",Portland,United States,Cumberland,1037118,...,0,StreetAddress,M,100.0,-70.256668,43.657432,HSIP USA_ZIP4 Composite,1 CITY CTR,100 N TRYON ST,6420
2,3,66 Main Street,28,11,0,<None>,Ellsworth,United States,Hancock,75152,...,0,PointAddress,M,100.0,-68.424621,44.541326,HSIP USA_ZIP4 Composite,66 MAIN ST,2 ELM ST,1970
3,4,1 Lincoln St. Fl 1,0,11,14460,"Boston-Cambridge-Newton, MA-NH",Boston,United States,Suffolk,112389655,...,1,PointAddress,M,100.0,-71.057959,42.352824,HSIP USA_ZIP4 Composite,1 LINCOLN ST FL 1,1 LINCOLN ST FL 1,2901
4,5,1414 Massachusetts Avenue,7332,11,14460,"Boston-Cambridge-Newton, MA-NH",Cambridge,United States,Middlesex,1415083,...,0,StreetAddress,T,100.0,-71.118913,42.373832,HSIP USA_ZIP4 Composite,1414 MASSACHUSETTS AVE,100 N TRYON ST,3807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88058,88059,4200 Sw 34th St Unit A,133,11,23540,"Gainesville, FL",Gainesville,United States,Alachua,177,...,0,PointAddress,M,100.0,-82.372153,29.614166,HSIP USA_ZIP4 Composite,4200 SW 34TH ST,4705 W US HIGHWAY 90,0
88059,88060,1001 Craig Rd,14,21,41180,"St. Louis, MO-IL",Saint Louis,United States,St. Louis,0,...,0,PointAddress,M,100.0,-90.436247,38.672542,HSIP USA_ZIP4 Composite,1001 CRAIG RD,315 WEST PUBLIC SQUARE,0
88060,88061,51 Donahue Avenue Suite 115,17,11,34060,"Morgantown, WV",Morgantown,United States,Monongalia,12858,...,0,StreetAddress,M,89.0,-79.921480,39.651497,HSIP USA_ZIP4 Composite,51 DONNA AVE,301 VIRGINIA AVE,0
88061,88062,4 Northridge Dr Suite 106,3,12,0,<None>,Buckhannon,United States,Upshur,639,...,0,Postal,M,100.0,-80.226518,38.983763,HSIP USA_ZIP4 Composite,4 NORTHRIDGE DR STE 106,107 PIKE ST,0
88062,88063,1450 High Street,238,11,21660,"Eugene, OR",Eugene,United States,Lane,95780,...,0,PointAddress,M,100.0,-123.088238,44.044050,HSIP USA_ZIP4 Composite,1450 HIGH ST,1301 A ST,0

In [3]:
#check for missing values
df.isnull().sum()

OBJECTID                  0
ADDRESBR                  0
BRNUM                     0
BRSERTYP                  0
CBSABR                    0
CBSANAMB                  0
CITYBR                    0
CNTRYNAB                  0
CNTYNAMB                  0
DEPSUMBR                  0
GEOCODE_CENSUS_TRACT      0
NAMEBR                    0
STALPBR                   0
STCNTYBR                  0
STNAMEBR                  0
UNINUMBR                  0
ZIPBR                     0
CERT                      0
ADDRESS                   0
ASSET                     0
BKCLASS                   0
CITY                      0
CNTRYNA                   0
DENOVO                    0
DEPDOM                    0
NAMEFULL                  0
NAMEHCR                   0
REGAGNT                   0
REPDTE                    0
RSSDID                    0
STALP                     0
STCNTY                    0
STNAME                    0
ZIP                       0
BKMO                      0
LOC_NAME                  0
STATUS                  139
SCORE                   139
x                         0
y                         0
GeocodeSource             0
STD_ADDR_BR               0
STD_ADDR                  0
ZIP4BR                    0
dtype: int64

In [4]:
# Drop rows where 'STATUS' and 'SCORE' columns have missing values
df = df.dropna(subset=['STATUS', 'SCORE'])

#Verify for missing values removed
df.isnull().sum()

OBJECTID                0
ADDRESBR                0
BRNUM                   0
BRSERTYP                0
CBSABR                  0
CBSANAMB                0
CITYBR                  0
CNTRYNAB                0
CNTYNAMB                0
DEPSUMBR                0
GEOCODE_CENSUS_TRACT    0
NAMEBR                  0
STALPBR                 0
STCNTYBR                0
STNAMEBR                0
UNINUMBR                0
ZIPBR                   0
CERT                    0
ADDRESS                 0
ASSET                   0
BKCLASS                 0
CITY                    0
CNTRYNA                 0
DENOVO                  0
DEPDOM                  0
NAMEFULL                0
NAMEHCR                 0
REGAGNT                 0
REPDTE                  0
RSSDID                  0
STALP                   0
STCNTY                  0
STNAME                  0
ZIP                     0
BKMO                    0
LOC_NAME                0
STATUS                  0
SCORE                   0
x                       0
y                       0
GeocodeSource           0
STD_ADDR_BR             0
STD_ADDR                0
ZIP4BR                  0
dtype: int64

In [5]:
#Drop cells with 0 Deposits
df = df[df['DEPSUMBR'] != 0]
df

,OBJECTID,ADDRESBR,BRNUM,BRSERTYP,CBSABR,CBSANAMB,CITYBR,CNTRYNAB,CNTYNAMB,DEPSUMBR,...,BKMO,LOC_NAME,STATUS,SCORE,x,y,GeocodeSource,STD_ADDR_BR,STD_ADDR,ZIP4BR
0,1,22 Main Street,7636,11,25540,"Hartford-West Hartford-East Hartford, CT",Southington,United States,Hartford,76878,...,0,PointAddress,M,100.0,-72.878648,41.601435,HSIP USA_ZIP4 Composite,22 MAIN ST,100 N TRYON ST,2501
1,2,One City Center,8203,11,38860,"Portland-South Portland, ME",Portland,United States,Cumberland,1037118,...,0,StreetAddress,M,100.0,-70.256668,43.657432,HSIP USA_ZIP4 Composite,1 CITY CTR,100 N TRYON ST,6420
2,3,66 Main Street,28,11,0,<None>,Ellsworth,United States,Hancock,75152,...,0,PointAddress,M,100.0,-68.424621,44.541326,HSIP USA_ZIP4 Composite,66 MAIN ST,2 ELM ST,1970
3,4,1 Lincoln St. Fl 1,0,11,14460,"Boston-Cambridge-Newton, MA-NH",Boston,United States,Suffolk,112389655,...,1,PointAddress,M,100.0,-71.057959,42.352824,HSIP USA_ZIP4 Composite,1 LINCOLN ST FL 1,1 LINCOLN ST FL 1,2901
4,5,1414 Massachusetts Avenue,7332,11,14460,"Boston-Cambridge-Newton, MA-NH",Cambridge,United States,Middlesex,1415083,...,0,StreetAddress,T,100.0,-71.118913,42.373832,HSIP USA_ZIP4 Composite,1414 MASSACHUSETTS AVE,100 N TRYON ST,3807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88057,88058,707 Main Street,2,11,35380,"New Orleans-Metairie, LA",Madisonville,United States,St. Tammany,2011,...,0,PointAddress,M,100.0,-90.156750,30.404540,HSIP USA_ZIP4 Composite,707 MAIN ST,205 N COLUMBIA ST,0
88058,88059,4200 Sw 34th St Unit A,133,11,23540,"Gainesville, FL",Gainesville,United States,Alachua,177,...,0,PointAddress,M,100.0,-82.372153,29.614166,HSIP USA_ZIP4 Composite,4200 SW 34TH ST,4705 W US HIGHWAY 90,0
88060,88061,51 Donahue Avenue Suite 115,17,11,34060,"Morgantown, WV",Morgantown,United States,Monongalia,12858,...,0,StreetAddress,M,89.0,-79.921480,39.651497,HSIP USA_ZIP4 Composite,51 DONNA AVE,301 VIRGINIA AVE,0
88061,88062,4 Northridge Dr Suite 106,3,12,0,<None>,Buckhannon,United States,Upshur,639,...,0,Postal,M,100.0,-80.226518,38.983763,HSIP USA_ZIP4 Composite,4 NORTHRIDGE DR STE 106,107 PIKE ST,0
88062,88063,1450 High Street,238,11,21660,"Eugene, OR",Eugene,United States,Lane,95780,...,0,PointAddress,M,100.0,-123.088238,44.044050,HSIP USA_ZIP4 Composite,1450 HIGH ST,1301 A ST,0

In [6]:
df.dtypes

OBJECTID                  int64
ADDRESBR                 object
BRNUM                     int64
BRSERTYP                  int64
CBSABR                    int64
CBSANAMB                 object
CITYBR                   object
CNTRYNAB                 object
CNTYNAMB                 object
DEPSUMBR                  int64
GEOCODE_CENSUS_TRACT      int64
NAMEBR                   object
STALPBR                  object
STCNTYBR                  int64
STNAMEBR                 object
UNINUMBR                  int64
ZIPBR                     int64
CERT                      int64
ADDRESS                  object
ASSET                     int64
BKCLASS                  object
CITY                     object
CNTRYNA                  object
DENOVO                    int64
DEPDOM                    int64
NAMEFULL                 object
NAMEHCR                  object
REGAGNT                  object
REPDTE                   object
RSSDID                    int64
STALP                    object
STCNTY                    int64
STNAME                   object
ZIP                       int64
BKMO                      int64
LOC_NAME                 object
STATUS                   object
SCORE                   float64
x                       float64
y                       float64
GeocodeSource            object
STD_ADDR_BR              object
STD_ADDR                 object
ZIP4BR                    int64
dtype: object

In [7]:
#Convert "REPDTE" to Date column
df['REPDTE'] = pd.to_datetime(df['REPDTE'])

# Convert to the desired format 'YYYY/MM/DD'
df['REPDTE'] = df['REPDTE'].dt.strftime('%Y/%m/%d')
df['REPDTE']

0        2018/06/30
1        2018/06/30
2        2018/06/30
3        2018/06/30
4        2018/06/30
            ...
88057    2018/06/30
88058    2018/06/30
88060    2018/06/30
88061    2018/06/30
88062    2018/06/30
Name: REPDTE, Length: 85116, dtype: object

In [8]:
#Drop irrelevant columns
drop_irrelevant_columns = ['x', 'y', 'GeocodeSource', 'BKMO']
df = df.drop(columns = drop_irrelevant_columns)
df

,OBJECTID,ADDRESBR,BRNUM,BRSERTYP,CBSABR,CBSANAMB,CITYBR,CNTRYNAB,CNTYNAMB,DEPSUMBR,...,STALP,STCNTY,STNAME,ZIP,LOC_NAME,STATUS,SCORE,STD_ADDR_BR,STD_ADDR,ZIP4BR
0,1,22 Main Street,7636,11,25540,"Hartford-West Hartford-East Hartford, CT",Southington,United States,Hartford,76878,...,NC,37119,North Carolina,28202,PointAddress,M,100.0,22 MAIN ST,100 N TRYON ST,2501
1,2,One City Center,8203,11,38860,"Portland-South Portland, ME",Portland,United States,Cumberland,1037118,...,NC,37119,North Carolina,28202,StreetAddress,M,100.0,1 CITY CTR,100 N TRYON ST,6420
2,3,66 Main Street,28,11,0,<None>,Ellsworth,United States,Hancock,75152,...,ME,23013,Maine,4843,PointAddress,M,100.0,66 MAIN ST,2 ELM ST,1970
3,4,1 Lincoln St. Fl 1,0,11,14460,"Boston-Cambridge-Newton, MA-NH",Boston,United States,Suffolk,112389655,...,MA,25025,Massachusetts,2111,PointAddress,M,100.0,1 LINCOLN ST FL 1,1 LINCOLN ST FL 1,2901
4,5,1414 Massachusetts Avenue,7332,11,14460,"Boston-Cambridge-Newton, MA-NH",Cambridge,United States,Middlesex,1415083,...,NC,37119,North Carolina,28202,StreetAddress,T,100.0,1414 MASSACHUSETTS AVE,100 N TRYON ST,3807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88057,88058,707 Main Street,2,11,35380,"New Orleans-Metairie, LA",Madisonville,United States,St. Tammany,2011,...,LA,22103,Louisiana,70433,PointAddress,M,100.0,707 MAIN ST,205 N COLUMBIA ST,0
88058,88059,4200 Sw 34th St Unit A,133,11,23540,"Gainesville, FL",Gainesville,United States,Alachua,177,...,FL,12023,Florida,32055,PointAddress,M,100.0,4200 SW 34TH ST,4705 W US HIGHWAY 90,0
88060,88061,51 Donahue Avenue Suite 115,17,11,34060,"Morgantown, WV",Morgantown,United States,Monongalia,12858,...,WV,54049,West Virginia,26554,StreetAddress,M,89.0,51 DONNA AVE,301 VIRGINIA AVE,0
88061,88062,4 Northridge Dr Suite 106,3,12,0,<None>,Buckhannon,United States,Upshur,639,...,WV,54001,West Virginia,26416,Postal,M,100.0,4 NORTHRIDGE DR STE 106,107 PIKE ST,0
88062,88063,1450 High Street,238,11,21660,"Eugene, OR",Eugene,United States,Lane,95780,...,WA,53053,Washington,98402,PointAddress,M,100.0,1450 HIGH ST,1301 A ST,0

In [9]:
#Replace <None> with a specific value like 'Unknown'
df['CBSANAMB'] = df['CBSANAMB'].replace('<None>', 'Unknown')
df

,OBJECTID,ADDRESBR,BRNUM,BRSERTYP,CBSABR,CBSANAMB,CITYBR,CNTRYNAB,CNTYNAMB,DEPSUMBR,...,STALP,STCNTY,STNAME,ZIP,LOC_NAME,STATUS,SCORE,STD_ADDR_BR,STD_ADDR,ZIP4BR
0,1,22 Main Street,7636,11,25540,"Hartford-West Hartford-East Hartford, CT",Southington,United States,Hartford,76878,...,NC,37119,North Carolina,28202,PointAddress,M,100.0,22 MAIN ST,100 N TRYON ST,2501
1,2,One City Center,8203,11,38860,"Portland-South Portland, ME",Portland,United States,Cumberland,1037118,...,NC,37119,North Carolina,28202,StreetAddress,M,100.0,1 CITY CTR,100 N TRYON ST,6420
2,3,66 Main Street,28,11,0,Unknown,Ellsworth,United States,Hancock,75152,...,ME,23013,Maine,4843,PointAddress,M,100.0,66 MAIN ST,2 ELM ST,1970
3,4,1 Lincoln St. Fl 1,0,11,14460,"Boston-Cambridge-Newton, MA-NH",Boston,United States,Suffolk,112389655,...,MA,25025,Massachusetts,2111,PointAddress,M,100.0,1 LINCOLN ST FL 1,1 LINCOLN ST FL 1,2901
4,5,1414 Massachusetts Avenue,7332,11,14460,"Boston-Cambridge-Newton, MA-NH",Cambridge,United States,Middlesex,1415083,...,NC,37119,North Carolina,28202,StreetAddress,T,100.0,1414 MASSACHUSETTS AVE,100 N TRYON ST,3807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88057,88058,707 Main Street,2,11,35380,"New Orleans-Metairie, LA",Madisonville,United States,St. Tammany,2011,...,LA,22103,Louisiana,70433,PointAddress,M,100.0,707 MAIN ST,205 N COLUMBIA ST,0
88058,88059,4200 Sw 34th St Unit A,133,11,23540,"Gainesville, FL",Gainesville,United States,Alachua,177,...,FL,12023,Florida,32055,PointAddress,M,100.0,4200 SW 34TH ST,4705 W US HIGHWAY 90,0
88060,88061,51 Donahue Avenue Suite 115,17,11,34060,"Morgantown, WV",Morgantown,United States,Monongalia,12858,...,WV,54049,West Virginia,26554,StreetAddress,M,89.0,51 DONNA AVE,301 VIRGINIA AVE,0
88061,88062,4 Northridge Dr Suite 106,3,12,0,Unknown,Buckhannon,United States,Upshur,639,...,WV,54001,West Virginia,26416,Postal,M,100.0,4 NORTHRIDGE DR STE 106,107 PIKE ST,0
88062,88063,1450 High Street,238,11,21660,"Eugene, OR",Eugene,United States,Lane,95780,...,WA,53053,Washington,98402,PointAddress,M,100.0,1450 HIGH ST,1301 A ST,0

In [10]:
Cleaned_FDIC_Insured_Banks_path = 'Data\Cleaned_FDIC_Insured_Banks.csv'

df.to_csv(Cleaned_FDIC_Insured_Banks_path, index=False)

In [11]:
df = pd.read_csv(r"Data\Cleaned_FDIC_Insured_Banks.csv")
df

,OBJECTID,ADDRESBR,BRNUM,BRSERTYP,CBSABR,CBSANAMB,CITYBR,CNTRYNAB,CNTYNAMB,DEPSUMBR,...,STALP,STCNTY,STNAME,ZIP,LOC_NAME,STATUS,SCORE,STD_ADDR_BR,STD_ADDR,ZIP4BR
0,1,22 Main Street,7636,11,25540,"Hartford-West Hartford-East Hartford, CT",Southington,United States,Hartford,76878,...,NC,37119,North Carolina,28202,PointAddress,M,100.0,22 MAIN ST,100 N TRYON ST,2501
1,2,One City Center,8203,11,38860,"Portland-South Portland, ME",Portland,United States,Cumberland,1037118,...,NC,37119,North Carolina,28202,StreetAddress,M,100.0,1 CITY CTR,100 N TRYON ST,6420
2,3,66 Main Street,28,11,0,Unknown,Ellsworth,United States,Hancock,75152,...,ME,23013,Maine,4843,PointAddress,M,100.0,66 MAIN ST,2 ELM ST,1970
3,4,1 Lincoln St. Fl 1,0,11,14460,"Boston-Cambridge-Newton, MA-NH",Boston,United States,Suffolk,112389655,...,MA,25025,Massachusetts,2111,PointAddress,M,100.0,1 LINCOLN ST FL 1,1 LINCOLN ST FL 1,2901
4,5,1414 Massachusetts Avenue,7332,11,14460,"Boston-Cambridge-Newton, MA-NH",Cambridge,United States,Middlesex,1415083,...,NC,37119,North Carolina,28202,StreetAddress,T,100.0,1414 MASSACHUSETTS AVE,100 N TRYON ST,3807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85111,88058,707 Main Street,2,11,35380,"New Orleans-Metairie, LA",Madisonville,United States,St. Tammany,2011,...,LA,22103,Louisiana,70433,PointAddress,M,100.0,707 MAIN ST,205 N COLUMBIA ST,0
85112,88059,4200 Sw 34th St Unit A,133,11,23540,"Gainesville, FL",Gainesville,United States,Alachua,177,...,FL,12023,Florida,32055,PointAddress,M,100.0,4200 SW 34TH ST,4705 W US HIGHWAY 90,0
85113,88061,51 Donahue Avenue Suite 115,17,11,34060,"Morgantown, WV",Morgantown,United States,Monongalia,12858,...,WV,54049,West Virginia,26554,StreetAddress,M,89.0,51 DONNA AVE,301 VIRGINIA AVE,0
85114,88062,4 Northridge Dr Suite 106,3,12,0,Unknown,Buckhannon,United States,Upshur,639,...,WV,54001,West Virginia,26416,Postal,M,100.0,4 NORTHRIDGE DR STE 106,107 PIKE ST,0
85115,88063,1450 High Street,238,11,21660,"Eugene, OR",Eugene,United States,Lane,95780,...,WA,53053,Washington,98402,PointAddress,M,100.0,1450 HIGH ST,1301 A ST,0

In [12]:
pip install --upgrade category_encoders

Requirement already satisfied: category_encoders in c:\users\prate\anaconda3\lib\site-packages (2.6.3)
Requirement already satisfied: numpy>=1.14.0 in c:\users\prate\anaconda3\lib\site-packages (from category_encoders) (1.24.3)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\prate\anaconda3\lib\site-packages (from category_encoders) (1.3.0)
Requirement already satisfied: scipy>=1.0.0 in c:\users\prate\anaconda3\lib\site-packages (from category_encoders) (1.11.1)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\prate\anaconda3\lib\site-packages (from category_encoders) (0.14.0)
Requirement already satisfied: pandas>=1.0.5 in c:\users\prate\anaconda3\lib\site-packages (from category_encoders) (2.0.3)
Requirement already satisfied: patsy>=0.5.1 in c:\users\prate\anaconda3\lib\site-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prate\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\prate\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\prate\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3)
Requirement already satisfied: six in c:\users\prate\anaconda3\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\prate\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\prate\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (2.2.0)
Requirement already satisfied: packaging>=21.3 in c:\users\prate\anaconda3\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (23.1)
Note: you may need to restart the kernel to use updated packages.

In [13]:
train, test = train_test_split(df, test_size=0.3, random_state=42)

In [14]:
X_train = train.drop(columns='SCORE')
y_train = train['SCORE']
X_test = test.drop(columns='SCORE')
y_test = test['SCORE']

#### ENCODING ALL THE CATEGORICAL COLUMNS WITH THE HELP OF TARGET ENCODING AND ONE HOT ENCODING BELOW

1) Detecting categorical columns and trying to encode them

2) Using target encoding and hot encoding on the categorical columns

3) If the category has less than 10 classes then One hot encoding is used otherwise target encoding is done

In [15]:
import os
from sklearn.preprocessing import OneHotEncoder
from category_encoders import TargetEncoder
import pandas as pd
from copy import deepcopy
import dill

# Columns to drop from ML models
cols_to_drop = []
# Categorical encoders dictionary
cat_encoders = {}
# New categorical (encoded) columns
cat_enc_columns = []

# Helper function for concatenating results
def apply_encoding(enc, X, columns, index):
    result = enc.transform(X)
    return pd.DataFrame(result, columns=columns, index=index)

# Encoding loop
for col in X_train.select_dtypes(include=['object']).columns:
    if X_train[col].nunique() < 10:  # One-hot encoding for low-cardinality features
        print("One-hot encoding of ", col)
        enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
        enc.fit(X_train[[col]])
        ohe_columns = [f"{col}_{x}" for x in enc.categories_[0]]
        
        # Apply one-hot encoding to train and test
        X_train[ohe_columns] = apply_encoding(enc, X_train[[col]], ohe_columns, X_train.index)
        X_test[ohe_columns] = apply_encoding(enc, X_test[[col]], ohe_columns, X_test.index)
        
        # Store the encoder
        cat_encoders[col] = [deepcopy(enc), "ohe"]
        cat_enc_columns.extend(ohe_columns)
    else:  # Target encoding for high-cardinality features
        print("Target Encoding of ", col)
        enc = TargetEncoder()
        enc.fit(X_train[col], y=y_train)
        new_col_name = f"{col}_trg"
        
        # Apply target encoding to train and test
        X_train[new_col_name] = enc.transform(X_train[[col]])
        X_test[new_col_name] = enc.transform(X_test[[col]])
        
        # Store the encoder
        cat_encoders[col] = [deepcopy(enc), "trg"]
        cat_enc_columns.append(new_col_name)
    
    # Track columns to drop
    cols_to_drop.append(col)

# Drop original categorical columns
X_train.drop(cols_to_drop, axis=1, inplace=True)
X_test.drop(cols_to_drop, axis=1, inplace=True)

Target Encoding of  ADDRESBR
Target Encoding of  CBSANAMB
Target Encoding of  CITYBR
One-hot encoding of  CNTRYNAB
Target Encoding of  CNTYNAMB
Target Encoding of  NAMEBR
Target Encoding of  STALPBR

C:\Users\prate\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Target Encoding of  STNAMEBR
Target Encoding of  ADDRESS
One-hot encoding of  BKCLASS
Target Encoding of  CITY

C:\Users\prate\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Target Encoding of  CNTRYNA
Target Encoding of  NAMEFULL
Target Encoding of  NAMEHCR
One-hot encoding of  REGAGNT

C:\Users\prate\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\prate\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\prate\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

One-hot encoding of  REPDTE
Target Encoding of  STALP
Target Encoding of  STNAME
Target Encoding of  LOC_NAME
One-hot encoding of  STATUS
Target Encoding of  STD_ADDR_BR
Target Encoding of  STD_ADDR

In [16]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59581 entries, 32555 to 15795
Data columns (total 50 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   OBJECTID                             59581 non-null  int64
 1   BRNUM                                59581 non-null  int64
 2   BRSERTYP                             59581 non-null  int64
 3   CBSABR                               59581 non-null  int64
 4   DEPSUMBR                             59581 non-null  int64
 5   GEOCODE_CENSUS_TRACT                 59581 non-null  int64
 6   STCNTYBR                             59581 non-null  int64
 7   UNINUMBR                             59581 non-null  int64
 8   ZIPBR                                59581 non-null  int64
 9   CERT                                 59581 non-null  int64
 10  ASSET                                59581 non-null  int64
 11  DENOVO                               59581 non-null  int64
 12  DEPDOM                               59581 non-null  int64
 13  RSSDID                               59581 non-null  int64
 14  STCNTY                               59581 non-null  int64
 15  ZIP                                  59581 non-null  int64
 16  ZIP4BR                               59581 non-null  int64
 17  ADDRESBR_trg                         59581 non-null  float64
 18  CBSANAMB_trg                         59581 non-null  float64
 19  CITYBR_trg                           59581 non-null  float64
 20  CNTRYNAB_Northern Mariana Islands    59581 non-null  float64
 21  CNTRYNAB_Puerto Rico                 59581 non-null  float64
 22  CNTRYNAB_United States               59581 non-null  float64
 23  CNTRYNAB_Virgin Islands Of The U.S.  59581 non-null  float64
 24  CNTYNAMB_trg                         59581 non-null  float64
 25  NAMEBR_trg                           59581 non-null  float64
 26  STALPBR_trg                          59581 non-null  float64
 27  STNAMEBR_trg                         59581 non-null  float64
 28  ADDRESS_trg                          59581 non-null  float64
 29  BKCLASS_N                            59581 non-null  float64
 30  BKCLASS_NM                           59581 non-null  float64
 31  BKCLASS_OI                           59581 non-null  float64
 32  BKCLASS_SB                           59581 non-null  float64
 33  BKCLASS_SL                           59581 non-null  float64
 34  BKCLASS_SM                           59581 non-null  float64
 35  CITY_trg                             59581 non-null  float64
 36  CNTRYNA_trg                          59581 non-null  float64
 37  NAMEFULL_trg                         59581 non-null  float64
 38  NAMEHCR_trg                          59581 non-null  float64
 39  REGAGNT_FDIC                         59581 non-null  float64
 40  REGAGNT_FED                          59581 non-null  float64
 41  REGAGNT_OCC                          59581 non-null  float64
 42  REPDTE_2018/06/30                    59581 non-null  float64
 43  STALP_trg                            59581 non-null  float64
 44  STNAME_trg                           59581 non-null  float64
 45  LOC_NAME_trg                         59581 non-null  float64
 46  STATUS_M                             59581 non-null  float64
 47  STATUS_T                             59581 non-null  float64
 48  STD_ADDR_BR_trg                      59581 non-null  float64
 49  STD_ADDR_trg                         59581 non-null  float64
dtypes: float64(33), int64(17)
memory usage: 23.2 MB

##### After Encoding, as these columns are not further needed so dropping them.

In [18]:
X_train.drop(['ADDRESBR_trg','CBSANAMB_trg','CITYBR_trg','CNTYNAMB_trg','CNTYNAMB_trg',
              'NAMEBR_trg','STALPBR_trg','STNAMEBR_trg','ADDRESS_trg','CITY_trg','CNTRYNA_trg',
              'NAMEFULL_trg','NAMEHCR_trg','STALP_trg','STNAME_trg','LOC_NAME_trg','STD_ADDR_BR_trg','STD_ADDR_trg'],
             axis=1,inplace=True)

In [19]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59581 entries, 32555 to 15795
Data columns (total 33 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   OBJECTID                             59581 non-null  int64
 1   BRNUM                                59581 non-null  int64
 2   BRSERTYP                             59581 non-null  int64
 3   CBSABR                               59581 non-null  int64
 4   DEPSUMBR                             59581 non-null  int64
 5   GEOCODE_CENSUS_TRACT                 59581 non-null  int64
 6   STCNTYBR                             59581 non-null  int64
 7   UNINUMBR                             59581 non-null  int64
 8   ZIPBR                                59581 non-null  int64
 9   CERT                                 59581 non-null  int64
 10  ASSET                                59581 non-null  int64
 11  DENOVO                               59581 non-null  int64
 12  DEPDOM                               59581 non-null  int64
 13  RSSDID                               59581 non-null  int64
 14  STCNTY                               59581 non-null  int64
 15  ZIP                                  59581 non-null  int64
 16  ZIP4BR                               59581 non-null  int64
 17  CNTRYNAB_Northern Mariana Islands    59581 non-null  float64
 18  CNTRYNAB_Puerto Rico                 59581 non-null  float64
 19  CNTRYNAB_United States               59581 non-null  float64
 20  CNTRYNAB_Virgin Islands Of The U.S.  59581 non-null  float64
 21  BKCLASS_N                            59581 non-null  float64
 22  BKCLASS_NM                           59581 non-null  float64
 23  BKCLASS_OI                           59581 non-null  float64
 24  BKCLASS_SB                           59581 non-null  float64
 25  BKCLASS_SL                           59581 non-null  float64
 26  BKCLASS_SM                           59581 non-null  float64
 27  REGAGNT_FDIC                         59581 non-null  float64
 28  REGAGNT_FED                          59581 non-null  float64
 29  REGAGNT_OCC                          59581 non-null  float64
 30  REPDTE_2018/06/30                    59581 non-null  float64
 31  STATUS_M                             59581 non-null  float64
 32  STATUS_T                             59581 non-null  float64
dtypes: float64(16), int64(17)
memory usage: 15.5 MB

In [20]:
X_test.drop(['ADDRESBR_trg','CBSANAMB_trg','CITYBR_trg','CNTYNAMB_trg','CNTYNAMB_trg','NAMEBR_trg',
             'STALPBR_trg','STNAMEBR_trg','ADDRESS_trg','CITY_trg','CNTRYNA_trg','NAMEFULL_trg','NAMEHCR_trg',
             'STALP_trg','STNAME_trg','LOC_NAME_trg','STD_ADDR_BR_trg','STD_ADDR_trg'],
            axis=1,inplace=True)